slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan

    # 기본 로컬라이제이션 설정
    mode: localization
    map_file_name: "/home/data_file/slam/my_slam_map_0411_1558.posegraph"  # 런치 파일에서 전달받을 예정
    map_start_pose: [0.0, 0.0, 0.0]

    use_sim_time: false
    debug_logging: false
    transform_publish_period: 0.02
    resolution: 0.05

    # 레이저 범위
    min_laser_range: 0.1
    max_laser_range: 16.0

    # 일반 설정
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    do_loop_closing: false  # localization에선 비활성화
    loop_search_maximum_distance: 3.0

    # Correlation parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Scan Matcher
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

